version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=objectstorage
      - MYSQL_USER=storage
      - MYSQL_PASSWORD=asdfjkl;
    ports:
      - 3306:3306
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app
    # environment:
    #   - DATABASE_HOST=127.0.0.1
    #   - DB_USER=root
    #   - DB_PASSWORD=password
    #   - MYSQL_DATABASE=objectstorage

# version: "3.2"

# services:
#   webapi:
#     build:
#       context: ./
#       args:
#         JAR_APP: objectstorage-0.0.1-SNAPSHOT.jar
#
#     # restart: on-failure
#     image: backend
#
#     depends_on:
#       - database
#
#     environment:
#       DATABASE_HOST: localhost
#       DDL_MODE: none
#       DB_USER: root
#
#   database:
#     image: mysql:latest
#     restart: on-failure
#     ports:
#     - 127.0.0.1:3306:3306
#     volumes:
#       - ./db:/var/lib/mysql:rw
#
#     environment:
#       MYSQL_DATABASE: objectstorage
#       MYSQL_ROOT_PASSWORD: programsicom
